---
# -------------------------------
# CONFIGURE HOSTS NETWORKING
# -------------------------------

- name: Add entries to /etc/hosts
  lineinfile: 
    dest: /etc/hosts
    line: "{{ item.ip }} {{ item.hostname }}"
  with_items:
    - { ip: "10.0.0.10", hostname: "master" }
    - { ip: "10.0.0.11", hostname: "worker1" }
    - { ip: "10.0.0.12", hostname: "worker2" }