---
- hosts: all:!master
  become: true
  tasks:

# -------------------------------
# IMPORTS
# -------------------------------
    - import_tasks: hosts.yml
    - import_tasks: common.yml

# -----------------------------
# WORKER NODE CONFIGURATION
# -----------------------------
    - name: Create guest_share directory
      file:
        path: /home/vagrant/guest_share
        state: directory

    - name: Join the cluster 
      shell: sudo sh -c "cat /home/vagrant/guest_share/token | sh"